version: '2'
services:
  provider_oauth2:
    restart: always
    image: ccr.ccs.tencentyun.com/lhb-msos/provider-manager-user:0.3.1
    container_name: provider-manager-user
    ports:
      - 10000:10000
    network_mode: "host" # 与宿主机共有一个IP