version: '2'
services:
  provider-manager-user:
    restart: always
    image: ccr.ccs.tencentyun.com/lhb-msos/provider-manager-user:0.3.0
    container_name: provider-manager-user
    ports:
      - 10000:10000
    networks:
      - provider-manager-user_network
#配置网络
networks:
  provider-manager-user_network: