version: '2'
services:
  provider_oauth2:
    restart: always
    image: ccr.ccs.tencentyun.com/lhb-msos/provider-oauth2:0.3.0
    container_name: provider-oauth2
    ports:
      - 10010:10010
    networks:
      - provider_oauth2_network
#配置网络
networks:
  provider_oauth2_network: