version: '2'
services:
  provider_oauth2:
    restart: always
    image: ccr.ccs.tencentyun.com/lhb-msos/consumer-help-center:0.3.1
    container_name: consumer-help-center
    ports:
      - 12000:12000
    network_mode: "host" # 与宿主机共有一个IP
    networks:
      - consumer_help_center_network
# 配置网络
networks:
  consumer_help_center_network: