version: '2'
services:
  provider-app-user:
    restart: always
    image: ccr.ccs.tencentyun.com/lhb-msos/provider-app-user:0.3.0
    container_name: provider-app-user
    ports:
      - 10040:10040
    networks:
      - provider-app-user_network
#配置网络
networks:
  provider-app-user_network: