version: '2'
services:
  provider-gateway:
    restart: always
    image: ccr.ccs.tencentyun.com/lhb-msos/provider-gateway:0.3.0
    container_name: provider-gateway
    ports:
      - 10020:10020
    networks:
      - provider-gateway_network
#配置网络
networks:
  provider-gateway_network: