version: '2'
services:
  provider-gateway:
    restart: always
    image: 192.168.1.103:3001/provider-gateway
    container_name: provider-gateway
    ports:
      - 10020:10020
    networks:
      - provider-gateway_network
#配置网络
networks:
  provider-gateway_network: