version: '2'
services:
  provider-portal-user:
    restart: always
    image: 192.168.1.103:3001/provider-portal-user
    container_name: provider-portal-user
    ports:
      - 10030:10030
    networks:
      - provider-portal-user_network
#配置网络
networks:
  provider-portal-user_network: