version: '2'
services:
  provider_oauth2:
    restart: always
    image: ccr.ccs.tencentyun.com/lhb-msos/provider-portal-user:0.3.1
    container_name: provider-portal-user
    ports:
      - 10030:10030
    network_mode: "host" # 与宿主机共有一个IP
    networks:
      - provider_portal_user_network
# 配置网络
networks:
  provider_portal_user_network: