version: '2'
services:
  provider-portal-user:
    restart: always
    image: ccr.ccs.tencentyun.com/lhb-msos/provider-portal-user:0.3.0
    container_name: provider-portal-user
    ports:
      - 10030:10030
    networks:
      - provider-portal-user_network
#配置网络
networks:
  provider-portal-user_network: