server:
  port: 10000
spring:
  # nacos 服务注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.101:8848
    sentinel:
      transport:
        # sentinel服务器地址
        dashboard: 192.168.1.101:8858
      # 取消延迟加载
      eager: false
  # redis 配置
  redis:
    # redis一共16个库，本次项目使用第10个
    database: 10
    host: 47.95.206.128
    port: 3379
    # 超时时间 5s
    timeout: 5000
    password: 123456
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 8  #连接池中的最大空闲连接
        max-wait: -1s #连接池最大阻塞等待时间（使用负值表示没有限制)
        min-idle: 0  #连接池中的最小空闲连接
# 日志级别
logging:
  level:
    lhb.msos.provider.user: debug