spring:
  # nacos 服务注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.101:8848

dubbo:
  scan:
    # dubbo 实现类所在包
    base-packages: lhb.msos.provider.app.user
  # 协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受
  protocol:
    name: dubbo
    port: -1 # 端口为-1时，即是让dubbo自动分配端口
    serialization: kryo # 使用kryo序列化/反序列化工具
  registry:
    address: nacos://192.168.1.101:8848 #注册中心地址，格式为 注册中心组件名://注册中心访问地址
    timeout: 10000 # 10s的超时时间
  provider:
    # 开启轮询负载均衡
    loadbalance: roundrobin

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: lhb.msos.commons.domain, lhb.msos.provider.app.user.domain

# 日志级别
logging:
  level:
    lhb.msos.provider.app.user: debug


