spring:
  # nacos 服务注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.253.110:8848
    sentinel:
      transport:
        # sentinel服务器地址
        dashboard: 172.16.253.110:8858
      # 取消延迟加载
      eager: false
qiniu:
  accessKey: YOVO8DBqcU5j4fbhWSLea1h_4hjiegKwFnPZLISB
  secretKey: OnN5uImn2-NS0WGbs_2zcEL8huVqF0iLjsEAB2PY
  # 存储空间名称
  bucket: lhb-msos
  # 访问,根据机房位置从官网获取
  prefix: http://up-z2.qiniup.com
  # 外链域名
  domain: http://img.782272323.cn
# 日志级别
logging:
  level:
    lhb.msos.provider.qiniu.upload: debug